[[SentencePiece]]
arch = "aarch64"
git-tree-sha1 = "3ad4c1bf1e128003834a6ec33934d0fd1b5b4fdd"
os = "macos"

    [[SentencePiece.download]]
    sha256 = "bdfb40b6e1002e1269793eb5b6a880193cc515b4437a1a9e690ca2394f2463e4"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.aarch64-apple-darwin.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ad0d1dd3975a9625ec2a424fa9b1d45a4b100c2"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "8d28ae26bbf8c3be57911036663fd65f5a8098112ac492bbe0f3ef22e453343f"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.aarch64-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b0aad72e5a1d8f7233f194bfe9a1e9f12147ade"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "e53c95ea2849ff4b2ed630df5c8ffe63c32ddfa7f7e8d2551b287d9a61787d29"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.aarch64-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "335aa93dc6054fd5c9c3f33406119ec0247974e8"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "b5c13af3e9d740da806f410f2d25ae384b81d7c13e9d95cc13c753e78c0a5f5c"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.aarch64-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a02691c898b63e0ae52216441df3f0d3b2d544d"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "2a47929c60df58ea3aac47bb405131f7cfdd48f5570c8504ce48928eff6780a0"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.aarch64-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0aa9750b1600eda49dfa829e34abd1505346e7c"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "9ab69a4174b9d1f6469c4624ab95ef0969a112cc25a34e69ca81b22594d099e7"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7645a88148d0919000464eb12ad1763ae8cb7db1"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "16020deded10bd3ae21820fd44bdd523ccd1722675150e144add7d0082a8838a"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5fe352f50446e2fb157e1a4bb2b4d177220cd9b"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "d3a2b2ba2b1e4ef4f7d28dd9c082dd7a7352818cc1867ff56c535352ae639442"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f2b6b6936d9c7de72b7a49bf8217ce221852c8a"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "c4ce8538f741761d8ad6c1cb13a37a49825bfff7b6b3e89af68ab4ecdb39e837"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccb3d30c86cc619c92e413fc7f21851efff7633e"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "02444d895455903593e044d92766ae549e0cee8c1ec741e1f62b9a137d6c4d66"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e4aa646d6440ee2ad4869419bd649f9ad3075e3"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "35f3d6af18ccd5cd6f7c79705242f8f3650d6dc15aa645b2b3d94ee71bd58f7f"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faaff52eabf091fc87da89c291e7d462b34108d4"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "bb5255103a556b0fc36943d089c609f5e2e1d49da40bcdd8fbcd7dc4201e0c2e"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44144213e3d015d91666e115029c0a09c4791da0"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "e8dc544050055144cb3164f46d19d77f85d2912072f753d919564eefca06f11a"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "527cea65f131b83d0020afe7614bc47745f237d0"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "ce07e5bca4f11a3cef7fa0b657fea89d1151ecf4062d07446bc473e80cfc9c39"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f26e259f9b81f7c9c716cd604d2da8de08126f95"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "6a539f35d8e74f3c0c050ee8c8978ee8afe96be29abd48a2b90e2e19a6689155"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "511db2e8305c9092607e956a3960d2871ce62d5f"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "570e84b6f61e5b7e929050acac24b35cf307055f1002604889ffef6af9d73b57"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ea7fb3350fc28ed8ac109bc06d7bd362c8f5dd6"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "8ba4377a4815a0ce48787283af3822830cd69ef5f84f261548b7c392acbb6bda"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a99da6421ce9d8a9d1ab8467669bde3be1b0317"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "d829256289d438b22024eb66bd02129a914a39c6c52122dfe36bd8f2924ade0c"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-w64-mingw32-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ccde9997b0eb12770769b0df749e6ba943ffe7b"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "666588c9d2f845df87df0dea63c21655b506eceeaf76ed268430e5c1d6878307"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.i686-w64-mingw32-cxx11.tar.gz"
[[SentencePiece]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aefd46cb764c99a0fb12ac6f5d75ec06e5694830"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "8a9029cb7bc136b82d66245c5a2f6ef898a08727cce295242bc4af50363061a1"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "472387e761b21f3d2bc8661a0173362ce7c599a0"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "367c8fa3ad3936e2d8777608d63d212bb415924078233d4a357063b561d972dd"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
git-tree-sha1 = "0595c0517da75f9e3ffb1f312a3418d4cf24c9e5"
os = "macos"

    [[SentencePiece.download]]
    sha256 = "2db5df7be42fa172d1767c9e36674a3d54cba6c6da3890d9b50096c192936b50"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-apple-darwin.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4b0a6358d39f65071f39704b26e5218f4c0d5f2"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "fc945ed11f0f51a974efbfc6e15041f3d35eadcbd6c611bffafaaf07c4b19202"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db8ef70e99179f9cbc993f13765929144ed6b5a4"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "c7ce37a46de06fccf0728c61cd9ef4f3ab16e54bdaf68a8934fbcb93caf0121d"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "158a21e5b6c5a8f7d41de88897f5304a113fbc0f"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "f02114cf8d4a1a6060554d89128d1402b5ce1d21b87a383b25d6b7321d554ace"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9085cb49dc1255051c3555b539fb607063938b82"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "20f08124ebbecb31c75c44865baa251d71431174644f2739c3dd9e9a84d0d419"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
git-tree-sha1 = "bd01d2fe9e3644ea04c3346a33f0c51e16bfa36d"
os = "freebsd"

    [[SentencePiece.download]]
    sha256 = "c2618fb9e2e95e77e6f079e8091ff75583ef852c6c774dbcb11c65ebcb534ead"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-unknown-freebsd.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd0007be86924019eabe2b00005dd66efd23eeb5"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "a4ec02554275fc39ea73f42e2faa4d8b7189756f439254c8625d9fd3923aa2ce"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-w64-mingw32-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be7d0b54ef94b9e0d8504da8d85af48dfe90e0b6"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "d5a70120876a6c8211b0355610829bc2e1f556d1310b02204f81e759bb46d73d"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.99+0/SentencePiece.v0.1.99.x86_64-w64-mingw32-cxx11.tar.gz"
