[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c60250c5fcaf415e1e455cf5808724cb4de7e583"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "2570f255ba3fc70e1388a8a6fad445e52e3d456b28176c63538961d79deac2bf"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.aarch64-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba05a1e3c85f2857a649cd907d4649a06fb21007"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "07ae6c558b5eac2c2255974f4673d62f23fef78334ca8081dc452d507b674c11"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.aarch64-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd6fea758b559056019bbec51928639ee49fb9cc"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "87974025e27c09f25e38551577f7d86cc4338a610e20ab8e5fbe820c7d28aaf8"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.aarch64-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cba00f3912c2330e873bf543a4e7636fe630b05"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "cb4b9b23b0413ed60cb17ab82949818daec093bf166d7e628a0373b74a7cb5fa"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.aarch64-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a67c20a024cb61744a221b34a4fc99b86b58718"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "1e2697dc8dfdc20ba2b940f57df56f91a577e85c2de2039143a274d892a61e9e"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4f09c7815509716c9928571bd5317a55b223758"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "d36d9e3e891b80dac158297d7f893939da887b41e5769ac09dfbecb3e21cbf4f"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ce9f485b540882caee87057ca23d17d583fd74f"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "bdf7e87f0eeece8ce9c83f987f690b62507ee9ae0979c9025a5dae1e69b78d55"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SentencePiece]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc81830eff78ba5ba07555fdee0595a8b2bb1cba"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "a9e85458e831c29bfd240c41f377e0d0a06493b95de0f2a0e61e3b44a0d71d84"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ce608ef067bc5777598fd6d04950295747385ef"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "a61785b857074b55c7e7eebc3982ee5693b7532ce3bd5a43ba98cdb0d1d6c5eb"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b68d4d613178dcfdce205c86e7cb7e67df148a42"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "0718303c86822980a47d9654ca21296183181dfdca052ce043e68231a78701ac"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3613004d486412d2b2367de4fcb04aaf46ff7e09"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "cf147988750cc08f0dbf2d5bc3e32e844a222bf42a9453bd91e32f86f0353436"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a10c94292e9d5a5676638f92b6102ecd117abca5"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "3a6c3bef42f94c6f536a78cae204f2a9bec68b0ae4d6bcbbd6e8f0acf88a81dd"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07188fbdfbaac377511159e19eb3da1351f5b0fd"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "0b594cd9f35138b87daedba15ba01bf1a8a51cd1ce215351325a61ba36fcba25"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-w64-mingw32-cxx03.tar.gz"
[[SentencePiece]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7f568dc4c5c40eb3ffd45086af83dd7ba811de6"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "665e29b1ef6ffb6e77230d5407eaa7d1b4d41d183d29ccce2049cceca6421184"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.i686-w64-mingw32-cxx11.tar.gz"
[[SentencePiece]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ae407b6b2b69b79246266dc6c5a8aab0915cd06"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "1b94915d15449a06e9edcf92270bf4c0d564033d50347ba32e71dc12232fe9ee"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "311ae7941bb1a5dbc5c2ba74cb4383cac5820f26"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "d3fba443d04f51eabff6b3269604f54185abff22e3c2399e402e816269f982e2"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac1693f1edf4918061054a1c3f536d14dd8411c8"
os = "macos"

    [[SentencePiece.download]]
    sha256 = "22382f2b855da906b03662a5edc6bc52fe032fbd7878201563e05409aeaf1874"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-apple-darwin14-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02efae493722a495f3e5cc3138a0bd0ffaf57932"
os = "macos"

    [[SentencePiece.download]]
    sha256 = "dfef587c38a01abaac3c800644b004e3635832e43a92563ef6f82b97771a1fe2"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-apple-darwin14-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb6d3c4525556eb54742032f0e06e31ae514f0e4"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "cccadd5cb2506d4552d8a0a8bd27a1d813448524066fe1ddd50384ba5e417ff2"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-linux-gnu-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f78b8ed41e92f7a9762b82e640b75e4cf6cdbc6"
libc = "glibc"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "6ce5bc6b06379c1d0a362912c7edc8a5e64bc204dc66346ad44f539d840318bf"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-linux-gnu-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03969b2282527fcc25860c98d6e776f91f124f00"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "ec0e5cb467332ba25252396493433175ea8d125e4f9fa4c9ddd0b980675293f9"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-linux-musl-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6485d34179b92a039c1417612c46a6caeb7f953c"
libc = "musl"
os = "linux"

    [[SentencePiece.download]]
    sha256 = "291271ca2b245239b2e20463d91c1bc946f478f79b2e2e3830bb4aea8db560af"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-linux-musl-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f2343a462d1e7af7ecd8fd0e33f9a53b234e87"
os = "freebsd"

    [[SentencePiece.download]]
    sha256 = "ca2e5b3ba3ad7121072eb8d1a39bca7f04b8a27b692314d7ef4dde4f83ed0c12"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f5d76bfb4667f4c74cc5d5b8b59da9d7ef83e5a"
os = "freebsd"

    [[SentencePiece.download]]
    sha256 = "b53b865f3c8839b93d0b57b27a3fac0c9c8afec4bad072f8b83d79ab1c5cbd2f"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c61af01ba2013c93be646ac5b1e721638ca179b"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "2c45228f6d628759eb2214133e87ed46ffde1b0393ce8b23c6cbcbcb29a2ee4b"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-w64-mingw32-cxx03.tar.gz"
[[SentencePiece]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e2467c321886b8667b9a351dfba52b48b22c1df"
os = "windows"

    [[SentencePiece.download]]
    sha256 = "758ccac7b716f7143193b81feb6c2489af2c274e7f5757443bc46f2d1a08719c"
    url = "https://github.com/JuliaBinaryWrappers/SentencePiece_jll.jl/releases/download/SentencePiece-v0.1.92+0/SentencePiece.v0.1.92.x86_64-w64-mingw32-cxx11.tar.gz"
